[2025-03-20T16:39:08.831-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T16:39:08.841-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:38:19.819630+00:00 [queued]>
[2025-03-20T16:39:08.847-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:38:19.819630+00:00 [queued]>
[2025-03-20T16:39:08.847-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T16:39:08.865-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_datawrangling> on 2025-03-20 21:38:19.819630+00:00
[2025-03-20T16:39:08.872-0500] {standard_task_runner.py:72} INFO - Started process 209057 to run task
[2025-03-20T16:39:08.874-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl_dinamico', 'tarea_datawrangling', 'manual__2025-03-20T21:38:19.819630+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpn3l6no8b']
[2025-03-20T16:39:08.876-0500] {standard_task_runner.py:105} INFO - Job 6: Subtask tarea_datawrangling
[2025-03-20T16:39:08.912-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:38:19.819630+00:00 [running]> on host luis-GF65
[2025-03-20T16:39:08.970-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl_dinamico' AIRFLOW_CTX_TASK_ID='tarea_datawrangling' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T21:38:19.819630+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T21:38:19.819630+00:00'
[2025-03-20T16:39:08.971-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T16:39:27.112-0500] {data_wrangling.py:149} INFO - 1. Terminando formateo!!
[2025-03-20T16:39:38.452-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:39:46.711-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:39:46.726-0500] {data_wrangling.py:186} ERROR - Los clasificados como 'venta' no son considerablemente más caros que los de alquiler. Verificar información
[2025-03-20T16:39:46.726-0500] {data_wrangling.py:187} INFO - Los clasificados como 'venta' cuestan 1.0 veces más que los de alquiler
[2025-03-20T16:39:46.728-0500] {data_wrangling.py:199} INFO - 2. Terminando clasificación de propiedades con data inconsistente!!
[2025-03-20T16:40:30.514-0500] {data_wrangling.py:214} INFO - 3. Terminando obtención de dirección y precisión de coordenadas!!
[2025-03-20T16:40:48.355-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:40:49.687-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:40:49.688-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:40:51.941-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:04.739-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:07.504-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:09.693-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:10.064-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:16.821-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:16.831-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:41:16.832-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'area': 94.29% de 105
[2025-03-20T16:41:16.835-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:41:16.836-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'dormitorios': 99.31% de 144
[2025-03-20T16:41:16.839-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:41:16.840-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'banos': 77.86% de 140
[2025-03-20T16:41:16.843-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:41:16.844-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'antiguedad': 91.30% de 46
[2025-03-20T16:41:16.844-0500] {data_wrangling.py:264} INFO - La variable area redujo 5 nulos
[2025-03-20T16:41:16.845-0500] {data_wrangling.py:264} INFO - La variable dormitorios redujo 14 nulos
[2025-03-20T16:41:16.846-0500] {data_wrangling.py:264} INFO - La variable banos redujo 10 nulos
[2025-03-20T16:41:16.846-0500] {data_wrangling.py:264} INFO - La variable antiguedad redujo 0 nulos
[2025-03-20T16:41:16.848-0500] {data_wrangling.py:273} INFO - 4. Terminando imputación de nulos de variables básicas con la descripción!!
[2025-03-20T16:41:22.966-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:41:24.175-0500] {data_wrangling.py:325} INFO - 5. Terminando imputación de nulos de coordenadas con la descripción!!
[2025-03-20T16:41:25.881-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T16:41:25.884-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T16:41:25.884-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl_dinamico, task_id=tarea_datawrangling, run_id=manual__2025-03-20T21:38:19.819630+00:00, execution_date=20250320T213819, start_date=20250320T213908, end_date=20250320T214125
[2025-03-20T16:41:25.940-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T16:41:25.949-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T16:41:25.970-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
