[2025-03-20T17:52:06.971-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T17:52:06.979-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T22:52:02.384148+00:00 [queued]>
[2025-03-20T17:52:06.984-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T22:52:02.384148+00:00 [queued]>
[2025-03-20T17:52:06.984-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T17:52:06.999-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-20 22:52:02.384148+00:00
[2025-03-20T17:52:07.007-0500] {standard_task_runner.py:72} INFO - Started process 250756 to run task
[2025-03-20T17:52:07.010-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-20T22:52:02.384148+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpfhexepx6']
[2025-03-20T17:52:07.011-0500] {standard_task_runner.py:105} INFO - Job 18: Subtask tarea_formateo
[2025-03-20T17:52:07.038-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T22:52:02.384148+00:00 [running]> on host luis-GF65
[2025-03-20T17:52:07.095-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T22:52:02.384148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T22:52:02.384148+00:00'
[2025-03-20T17:52:07.095-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T17:52:18.811-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-20T17:52:45.229-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T17:52:45.232-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T17:52:45.233-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-20T22:52:02.384148+00:00, execution_date=20250320T225202, start_date=20250320T225206, end_date=20250320T225245
[2025-03-20T17:52:45.307-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T17:52:45.314-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T17:52:45.315-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-20T17:54:29.449-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T17:54:29.455-0500] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T22:52:02.384148+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-03-20T17:54:29.455-0500] {local_task_job_runner.py:166} INFO - Task is not able to be run
